django/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('wrelays.urls')),
    path('admin/', admin.site.urls),
]

django/mysite/wrelays/urls.py
from django.urls import path

from . import views


app_name = 'wrelays'    #namespace for template urls

urlpatterns = [
    path('', views.index, name='index'),
    path('relays', views.index, name='index2'),
    path('<int:relay_id>/', views.detail, name='detail'),
    path('<int:relay_id>/on', views.on, name='on'),
    path('<int:relay_id>/off', views.off, name='off'),
    path('<int:relay_id>/toggle', views.toggle, name='toggle'),
    path('schedule', views.schedule, name='schedule'),
]

django/mysite/wrelays/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from relays import relays
import json
import atexit

    
r = relays.get_relays()
def exit_handler():
    relays.end()

relays.start()
atexit.register(exit_handler)



def get_status():
    relays = {}
    relays['relays'] = []
    relays['relays'] = r.status()
    return relays

def index(request, relay_id=None):
    #return HttpResponse("Hello, world. You're at the polls index. %s" % json.dumps(text, indent=4))
    return render(request, 'index.html', context=get_status())

def detail(request, relay_id):
    return HttpResponse("You're looking at relay %s." % relay_id)

def on(request, relay_id):
    r.on(relay_id)
    return HttpResponse("You're turning on relay %s." % relay_id)

def off(request, relay_id):
    r.off(relay_id)
    #r.override(question_id)
    return HttpResponse("You're turning off relay %s." % relay_id)

def toggle(request, relay_id):
    r.toggle(relay_id)
    return redirect('/')

def schedule(request):
    #return JsonResponse(relays.loadConfig(), safe=False)
    obj = {}
    obj['relays'] = relays.loadConfig()
    return render(request, 'schedule.html', context=obj)
    

django/mysite/wrelays/templates/index.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Mother Fuckin' Relays!</title>
</head>

<body>
    <div class="container-fluid">
        <h1>Relays</h1>
        <ul class="list-group">
            {% for r in relays %}
            <li class="list-group-item list-group-item-action">
                <a href="{% url 'wrelays:toggle' r.index %}">
                    <div>
                        {% if r.is_on %}
                        <img height=25px src="{% static "on.png" %}" alt="on">
                        {% else %}
                        <img height=25px src="{% static "off.png" %}" alt="off">
                        {% endif %}
                        {{r.name}}
                        {{r.override}}
                    </div>
            </li>
            {% endfor %}
        </ul>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
    <script>
        var time_utc = new Date().getTime();
        document.write(Date.now());
    </script>
</body>

</html>

django/mysite/wrelays/templates/schedule.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Relays!</title>
</head>

<body>
    <div class="container-fluid">
        <h1>Relays</h1>
        <ul class="list-group">
            {% for r in relays %}
            <li class="list-group-item list-group-item-action">
                    <div> {{ r.name }} </div>
                    {% for e in r.events %}
                        <div> {{ e.start }} {{ e.end }} </div>
                    {% endfor %}
            </li>
            {% endfor %}
        </ul>
    </div>

    

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
    <script>
        var time_utc = new Date().getTime();
        document.write(Date.now());
    </script>
</body>

</html>